x = package.loadlib("lua_egpkg.dll", "luaopen_egpkg")
x()
print(egpkg.calculayt(3, 1))
print(egpkg.whatever("great example"))
print(egpkg.statefulA())
print(egpkg.statefulA())
print(egpkg.statefulB())
print(egpkg.statefulA())
print(egpkg.statefulB())
print(counter())
print(counter())
print(counter())
print(egpkg.max(4, -2.5, "6.6", 1.1))
print(egpkg.max())