x = package.loadlib("lua_egpkg.dll", "luaopen_egpkg")
x()
print(egpkg.mafematikz.calculayt(3, 1))
print(egpkg.sztryng.whatever("great example"))
print(egpkg.stateful.statefulA())
print(egpkg.stateful.statefulA())
print(egpkg.stateful.statefulB())
print(egpkg.stateful.statefulA())
print(egpkg.stateful.statefulB())
print(egpkg.mafematikz.max(4, -2.5, "6.6", 1.1))
print(egpkg.mafematikz.max())